/**
 * Plugin Manifest — Single source of truth for all plugin registrations.
 *
 * Array order determines initialization order.
 *
 * Adding a new plugin:
 * 1. Add a PluginDescriptor entry here (import path, class name, default config)
 * 2. Optionally add the config key to KeepTrackPluginsConfiguration for type-safe access
 */
import type { PluginDescriptor } from './plugin-descriptor';
import { satInfoBoxOrbitalConfigurationDefaults } from './sat-info-box-orbital/sat-info-box-orbital-settings';

export const pluginManifest: PluginDescriptor[] = [
  // ── Always-enabled infrastructure ──────────────────────────────────────────
  {
    configKey: 'Telemetry',
    ossImport: () => import('./telemetry/telemetry'),
    ossClassName: 'Telemetry',
    proImport: () => import('../plugins-pro/telemetry/telemetry'),
    defaultConfig: { enabled: true },
    alwaysEnabled: true,
  },
  {
    configKey: 'SelectSatManager',
    ossImport: () => import('./select-sat-manager/select-sat-manager'),
    ossClassName: 'SelectSatManager',
    defaultConfig: { enabled: true },
    alwaysEnabled: true,
  },

  // ── Data plugins (must load before catalog) ──────────────────────────────
  {
    configKey: 'StarsPlugin',
    ossImport: () => import('./stars/stars-stub'),
    ossClassName: 'StarsPlugin',
    proImport: () => import('../plugins-pro/stars/stars-plugin'),
    proClassName: 'StarsPlugin',
    defaultConfig: { enabled: true },
  },

  // ── Core UI ────────────────────────────────────────────────────────────────
  {
    configKey: 'ScenarioManagementPlugin',
    ossImport: () => import('./scenario-management/scenario-management'),
    ossClassName: 'ScenarioManagementPlugin',
    defaultConfig: { enabled: true, order: 1 },
  },
  {
    configKey: 'TopMenu',
    ossImport: () => import('./top-menu/top-menu'),
    ossClassName: 'TopMenu',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'TimeSlider',
    ossImport: () => import('./time-slider/time-slider'),
    ossClassName: 'TimeSlider',
    defaultConfig: { enabled: true, order: 1001 },
  },
  {
    configKey: 'TooltipsPlugin',
    ossImport: () => import('./tooltips/tooltips'),
    ossClassName: 'TooltipsPlugin',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'UserAccountPlugin',
    ossImport: () => import('./user-account/user-account'),
    ossClassName: 'UserAccountPlugin',
    proImport: () => import('../plugins-pro/user-account/user-account'),
    defaultConfig: { enabled: true, order: 2 },
  },
  {
    configKey: 'DebugMenuPlugin',
    ossImport: () => import('./debug/debug'),
    ossClassName: 'DebugMenuPlugin',
    proImport: () => import('../plugins-pro/debug/debug'),
    defaultConfig: { enabled: true, order: 0 },
  },

  // ── Satellite Info Box ─────────────────────────────────────────────────────
  {
    configKey: 'SatInfoBoxCore',
    ossImport: () => import('./sat-info-box/sat-info-box'),
    ossClassName: 'SatInfoBox',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'SatInfoBoxActions',
    ossImport: () => import('./sat-info-box-actions/sat-info-box-actions'),
    ossClassName: 'SatInfoBoxActions',
    proImport: () => import('../plugins-pro/sat-info-box-actions/sat-info-box-actions'),
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'SatInfoBoxLinks',
    ossImport: () => import('./sat-info-box-links/sat-info-box-links'),
    ossClassName: 'SatInfoBoxLinks',
    proImport: () => import('../plugins-pro/sat-info-box-links/sat-info-box-links'),
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'SatInfoBoxOrbital',
    ossImport: () => import('./sat-info-box-orbital/sat-info-box-orbital'),
    ossClassName: 'SatInfoBoxOrbital',
    defaultConfig: satInfoBoxOrbitalConfigurationDefaults,
  },
  {
    configKey: 'SatInfoBoxManeuver',
    ossImport: () => import('./sat-info-box-orbit-guard/sat-info-box-orbit-guard'),
    ossClassName: 'SatInfoBoxOrbitGuard',
    defaultConfig: { enabled: false },
  },
  {
    configKey: 'SatInfoBoxObject',
    ossImport: () => import('./sat-info-box-object/sat-info-box-object'),
    ossClassName: 'SatInfoBoxObject',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'SatInfoBoxMission',
    ossImport: () => import('./sat-info-box-mission/sat-info-box-mission'),
    ossClassName: 'SatInfoBoxMission',
    proImport: () => import('../plugins-pro/sat-info-box-mission/sat-info-box-mission'),
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'SatInfoBoxSponsor',
    ossImport: () => import('./sat-info-box-sponsor/sat-info-box-sponsor'),
    ossClassName: 'SatInfoBoxSponsor',
    proImport: () => import('../plugins-pro/sat-info-box-sponsor/sat-info-box-sponsor'),
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'SatInfoBoxSensor',
    ossImport: () => import('./sat-info-box-sensor/sat-info-box-sensor'),
    ossClassName: 'SatInfoBoxSensor',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'DateTimeManager',
    ossImport: () => import('./date-time-manager/date-time-manager'),
    ossClassName: 'DateTimeManager',
    defaultConfig: { enabled: true },
  },

  // ── Top Menu Plugins (loaded right to left) ────────────────────────────────
  {
    configKey: 'GithubLinkPlugin',
    ossImport: () => import('./github-link/github-link'),
    ossClassName: 'GithubLinkPlugin',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'LinkedInLinkPlugin',
    ossImport: () => import('./linkedin-link/linkedin-link'),
    ossClassName: 'LinkedInLinkPlugin',
    defaultConfig: { enabled: false },
  },
  {
    configKey: 'ClassificationBar',
    ossImport: () => import('./classification-bar/classification-bar'),
    ossClassName: 'ClassificationBar',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'SoundToggle',
    ossImport: () => import('./sound-toggle/sound-toggle'),
    ossClassName: 'SoundToggle',
    defaultConfig: { enabled: true },
  },

  // ── Scene Plugins ──────────────────────────────────────────────────────────
  {
    configKey: 'EarthAtmosphere',
    ossImport: () => import('./earth-atmosphere/earth-atmosphere'),
    ossClassName: 'EarthAtmosphere',
    proImport: () => import('../plugins-pro/earth-atmosphere/earth-atmosphere'),
    defaultConfig: { enabled: true },
  },

  // ── Bottom Menu Plugins ────────────────────────────────────────────────────
  {
    configKey: 'SensorListPlugin',
    ossImport: () => import('./sensor-list/sensor-list'),
    ossClassName: 'SensorListPlugin',
    defaultConfig: { enabled: true, order: 10 },
  },
  {
    configKey: 'SensorInfoPlugin',
    ossImport: () => import('./sensor/sensor-info-plugin'),
    ossClassName: 'SensorInfoPlugin',
    defaultConfig: { enabled: true, order: 11 },
  },
  {
    configKey: 'CustomSensorPlugin',
    ossImport: () => import('./sensor/custom-sensor-plugin'),
    ossClassName: 'CustomSensorPlugin',
    defaultConfig: { enabled: true, order: 12 },
  },
  {
    configKey: 'SensorFov',
    ossImport: () => import('./sensor-fov/sensor-fov'),
    ossClassName: 'SensorFov',
    defaultConfig: { enabled: true, order: 13 },
  },
  {
    configKey: 'SensorSurvFence',
    ossImport: () => import('./sensor-surv/sensor-surv-fence'),
    ossClassName: 'SensorSurvFence',
    defaultConfig: { enabled: true, order: 14 },
  },
  {
    configKey: 'ShortTermFences',
    ossImport: () => import('./short-term-fences/short-term-fences'),
    ossClassName: 'ShortTermFences',
    defaultConfig: { enabled: true, order: 15 },
  },
  {
    configKey: 'LookAnglesPlugin',
    ossImport: () => import('./sensor/look-angles-plugin'),
    ossClassName: 'LookAnglesPlugin',
    defaultConfig: { enabled: true, order: 20 },
  },
  {
    configKey: 'LinkBudgetPlugin',
    ossImport: () => import('./link-budget/link-budget'),
    ossClassName: 'LinkBudgetPlugin',
    proImport: () => import('../plugins-pro/link-budget/link-budget'),
    defaultConfig: { enabled: false, order: 94 },
  },
  {
    configKey: 'MultiSiteLookAnglesPlugin',
    ossImport: () => import('./sensor/multi-site-look-angles-plugin'),
    ossClassName: 'MultiSiteLookAnglesPlugin',
    defaultConfig: { enabled: true, order: 21 },
  },
  {
    configKey: 'SensorTimeline',
    ossImport: () => import('./timeline-sensor/sensor-timeline'),
    ossClassName: 'SensorTimeline',
    defaultConfig: { enabled: true, order: 30 },
  },
  {
    configKey: 'SatelliteTimeline',
    ossImport: () => import('./timeline-satellite/satellite-timeline'),
    ossClassName: 'SatelliteTimeline',
    defaultConfig: { enabled: true, order: 31 },
  },
  {
    configKey: 'WatchlistPlugin',
    ossImport: () => import('./satellite-lists/satellite-lists'),
    ossClassName: 'WatchlistPlugin',
    proImport: () => import('../plugins-pro/satellite-lists/satellite-lists'),
    proClassName: 'SatelliteListsPlugin',
    defaultConfig: { enabled: true, order: 40 },
  },
  {
    configKey: 'WatchlistOverlay',
    ossImport: () => import('./satellite-lists/watchlist-overlay'),
    ossClassName: 'WatchlistOverlay',
    defaultConfig: { enabled: true, order: 41 },
  },
  {
    configKey: 'ReportsPlugin',
    ossImport: () => import('./reports/reports'),
    ossClassName: 'ReportsPlugin',
    defaultConfig: { enabled: true, order: 50 },
  },
  {
    configKey: 'PolarPlotPlugin',
    ossImport: () => import('./polar-plot/polar-plot'),
    ossClassName: 'PolarPlotPlugin',
    defaultConfig: { enabled: true, order: 60 },
  },
  {
    configKey: 'NextLaunchesPlugin',
    ossImport: () => import('./next-launches/next-launches'),
    ossClassName: 'NextLaunchesPlugin',
    defaultConfig: { enabled: true, order: 350 },
  },
  {
    configKey: 'EarthquakePlugin',
    ossImport: () => import('../plugins-pro/earthquake/earthquake'),
    ossClassName: 'EarthquakePlugin',
    defaultConfig: { enabled: true, order: 355 },
  },
  {
    configKey: 'FindSatPlugin',
    ossImport: () => import('./find-sat/find-sat'),
    ossClassName: 'FindSatPlugin',
    proImport: () => import('../plugins-pro/find-sat/find-sat'),
    proClassName: 'FindSatPro',
    defaultConfig: { enabled: true, order: 80 },
  },
  {
    configKey: 'ProximityOps',
    ossImport: () => import('./proximity-ops/proximity-ops'),
    ossClassName: 'ProximityOps',
    defaultConfig: { enabled: true, order: 81 },
  },
  {
    configKey: 'OrbitReferences',
    ossImport: () => import('./orbit-references/orbit-references'),
    ossClassName: 'OrbitReferences',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'Collisions',
    ossImport: () => import('./collisions/collisions'),
    ossClassName: 'Collisions',
    defaultConfig: { enabled: true, order: 90 },
  },
  {
    configKey: 'TocaPocaPlugin',
    ossImport: () => import('./toca-poca-plugin/toca-poca-plugin'),
    ossClassName: 'TocaPocaPlugin',
    proImport: () => import('../plugins-pro/toca-poca-plugin/toca-poca-plugin'),
    defaultConfig: { enabled: true, order: 82 },
  },
  {
    configKey: 'NeighborhoodWatch',
    ossImport: () => import('./neighborhood-watch/neighborhood-watch'),
    ossClassName: 'NeighborhoodWatch',
    proImport: () => import('../plugins-pro/neighborhood-watch/neighborhood-watch'),
    defaultConfig: { enabled: true, order: 83 },
  },
  {
    configKey: 'OrbitGuardMenuPlugin',
    ossImport: () => import('./orbit-guard-menu/orbit-guard-menu'),
    ossClassName: 'OrbitGuardMenuPlugin',
    defaultConfig: { enabled: false, order: 91 },
  },
  {
    configKey: 'Reentries',
    ossImport: () => import('./reentries/reentries'),
    ossClassName: 'Reentries',
    defaultConfig: { enabled: true, order: 92 },
  },
  {
    configKey: 'Breakup',
    ossImport: () => import('./breakup/breakup'),
    ossClassName: 'Breakup',
    defaultConfig: { enabled: true, order: 73 },
  },
  {
    configKey: 'DebrisScreening',
    ossImport: () => import('./debris-screening/debris-screening'),
    ossClassName: 'DebrisScreening',
    defaultConfig: { enabled: true, order: 280 },
  },
  {
    configKey: 'transponderChannelData',
    ossImport: () => import('./transponder-channel-data/transponder-channel-data'),
    ossClassName: 'TransponderChannelData',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'StkFileHandler',
    ossImport: () => import('./stk-file-handler/stk-file-handler'),
    ossClassName: 'StkFileHandler',
    proImport: () => import('../plugins-pro/stk-file-handler/stk-file-handler'),
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'CreateSat',
    ossImport: () => import('./create-sat/create-sat'),
    ossClassName: 'CreateSat',
    proImport: () => import('../plugins-pro/create-sat/create-sat'),
    proClassName: 'CreateSatPro',
    defaultConfig: { enabled: true, order: 70 },
  },
  {
    configKey: 'OemReaderPlugin',
    ossImport: () => import('./oem-reader/oem-reader'),
    ossClassName: 'OemReaderPlugin',
    proImport: () => import('../plugins-pro/oem-reader/oem-reader'),
    defaultConfig: { enabled: true, order: 71.5 },
  },
  {
    configKey: 'NeighborhoodHistoryPlugin',
    ossImport: () => import('./neighborhood-history/neighborhood-history'),
    ossClassName: 'NeighborhoodHistoryPlugin',
    proImport: () => import('../plugins-pro/neighborhood-history/neighborhood-history'),
    defaultConfig: { enabled: true, order: 71.6 },
  },
  {
    configKey: 'EditSat',
    ossImport: () => import('./edit-sat/edit-sat'),
    ossClassName: 'EditSat',
    defaultConfig: { enabled: true, order: 71 },
  },
  {
    configKey: 'NewLaunch',
    ossImport: () => import('./new-launch/new-launch'),
    ossClassName: 'NewLaunch',
    proImport: () => import('../plugins-pro/new-launch/new-launch'),
    proClassName: 'NewLaunchPro',
    defaultConfig: { enabled: true, order: 72 },
  },
  {
    configKey: 'MissilePlugin',
    ossImport: () => import('./missile/missile-plugin'),
    ossClassName: 'MissilePlugin',
    defaultConfig: { enabled: true, order: 74 },
  },
  {
    configKey: 'EarthCenteredView',
    ossImport: () => import('./earth-centered-view/earth-centered-view'),
    ossClassName: 'EarthCenteredView',
    defaultConfig: { enabled: true, order: 149 },
  },
  {
    configKey: 'SatelliteViewPlugin',
    ossImport: () => import('./satellite-view/satellite-view'),
    ossClassName: 'SatelliteViewPlugin',
    defaultConfig: { enabled: true, order: 151 },
  },
  {
    configKey: 'SatelliteFixedView',
    ossImport: () => import('./satellite-fixed-view/satellite-fixed-view'),
    ossClassName: 'SatelliteFixedView',
    defaultConfig: { enabled: true, order: 150 },
  },
  {
    configKey: 'FpsView',
    ossImport: () => import('./fps-view/fps-view'),
    ossClassName: 'FpsView',
    defaultConfig: { enabled: true, order: 152 },
  },
  {
    configKey: 'SatelliteFov',
    ossImport: () => import('./satellite-fov/satellite-fov'),
    ossClassName: 'SatelliteFov',
    proImport: () => import('../plugins-pro/satellite-fov/satellite-fov'),
    proClassName: 'SatelliteFovPro',
    defaultConfig: { enabled: true, order: 75 },
  },
  {
    configKey: 'StereoMap',
    ossImport: () => import('./stereo-map/stereo-map'),
    ossClassName: 'StereoMap',
    proImport: () => import('../plugins-pro/stereo-map/stereo-map'),
    proClassName: 'StereoMapPro',
    defaultConfig: { enabled: true, order: 150 },
  },
  {
    configKey: 'Planetarium',
    ossImport: () => import('./planetarium/planetarium'),
    ossClassName: 'Planetarium',
    proImport: () => import('../plugins-pro/planetarium/planetarium'),
    defaultConfig: { enabled: true, order: 155 },
  },
  {
    configKey: 'Astronomy',
    ossImport: () => import('./astronomy/astronomy'),
    ossClassName: 'Astronomy',
    proImport: () => import('../plugins-pro/astronomy/astronomy'),
    defaultConfig: { enabled: true, order: 156 },
  },
  {
    configKey: 'NightToggle',
    ossImport: () => import('./night-toggle/night-toggle'),
    ossClassName: 'NightToggle',
    defaultConfig: { enabled: true, order: 310 },
  },
  {
    configKey: 'DopsPlugin',
    ossImport: () => import('./dops/dops'),
    ossClassName: 'DopsPlugin',
    proImport: () => import('../plugins-pro/dops/dops'),
    proClassName: 'DopsPluginPro',
    defaultConfig: { enabled: true, order: 500 },
  },
  {
    configKey: 'SatConstellations',
    ossImport: () => import('./sat-constellations/sat-constellations'),
    ossClassName: 'SatConstellations',
    defaultConfig: { enabled: true, order: 230 },
  },
  {
    configKey: 'CountriesMenu',
    ossImport: () => import('./countries/countries'),
    ossClassName: 'CountriesMenu',
    defaultConfig: { enabled: true, order: 231 },
  },
  {
    configKey: 'ColorMenu',
    ossImport: () => import('./colors-menu/colors-menu'),
    ossClassName: 'ColorMenu',
    defaultConfig: { enabled: true, order: 232 },
  },
  {
    configKey: 'PlanetsMenuPlugin',
    ossImport: () => import('./planets-menu/planets-menu'),
    ossClassName: 'PlanetsMenuPlugin',
    defaultConfig: { enabled: true, order: 233 },
  },
  {
    configKey: 'Screenshot',
    ossImport: () => import('./screenshot/screenshot'),
    ossClassName: 'Screenshot',
    defaultConfig: { enabled: true, order: 450 },
  },
  {
    configKey: 'LaunchCalendar',
    ossImport: () => import('./launch-calendar/launch-calendar'),
    ossClassName: 'LaunchCalendar',
    defaultConfig: { enabled: true, order: 351 },
  },
  {
    configKey: 'TimeMachine',
    ossImport: () => import('./time-machine/time-machine'),
    ossClassName: 'TimeMachine',
    defaultConfig: { enabled: true, order: 250 },
  },
  {
    configKey: 'SatellitePhotos',
    ossImport: () => import('./satellite-photos/satellite-photos'),
    ossClassName: 'SatellitePhotos',
    defaultConfig: { enabled: true, order: 240 },
  },
  {
    configKey: 'ScreenRecorder',
    ossImport: () => import('./screen-recorder/screen-recorder'),
    ossClassName: 'ScreenRecorder',
    defaultConfig: { enabled: true, order: 451 },
  },
  {
    configKey: 'DataExportPlugin',
    ossImport: () => import('./data-export/data-export'),
    ossClassName: 'DataExportPlugin',
    proImport: () => import('../plugins-pro/data-export/data-export'),
    proClassName: 'DataExportPro',
    defaultConfig: { enabled: true, order: 420 },
  },
  {
    configKey: 'CloseObjectsPlugin',
    ossImport: () => import('./close-objects/close-objects'),
    ossClassName: 'CloseObjectsPlugin',
    proImport: () => import('../plugins-pro/close-objects/close-objects'),
    proClassName: 'CloseObjectsPro',
    defaultConfig: { enabled: true, order: 421 },
  },
  {
    configKey: 'BestPassPlugin',
    ossImport: () => import('./best-pass/best-pass'),
    ossClassName: 'BestPassPlugin',
    proImport: () => import('../plugins-pro/best-pass/best-pass'),
    proClassName: 'BestPassPro',
    defaultConfig: { enabled: true, order: 422 },
  },
  {
    configKey: 'OverflightPlugin',
    proImport: () => import('../plugins-pro/overflight/overflight'),
    proClassName: 'OverflightPlugin',
    defaultConfig: { enabled: true, order: 423 },
  },
  {
    configKey: 'EclipseSolarAnalysis',
    ossImport: () => import('./eclipse-solar-analysis/eclipse-solar-analysis'),
    ossClassName: 'EclipseSolarAnalysis',
    proImport: () => import('../plugins-pro/eclipse-solar-analysis/eclipse-solar-analysis'),
    defaultConfig: { enabled: true, order: 93 },
  },
  {
    configKey: 'ManeuverPlugin',
    ossImport: () => import('./maneuver/maneuver'),
    ossClassName: 'ManeuverPlugin',
    proImport: () => import('../plugins-pro/maneuver/maneuver'),
    defaultConfig: { enabled: false, order: 409 },
  },
  {
    configKey: 'InitialOrbitDeterminationPlugin',
    ossImport: () => import('./initial-orbit/initial-orbit'),
    ossClassName: 'InitialOrbitDeterminationPlugin',
    proImport: () => import('../plugins-pro/initial-orbit/initial-orbit'),
    defaultConfig: { enabled: false, order: 410 },
  },
  {
    configKey: 'Calculator',
    ossImport: () => import('./calculator/calculator'),
    ossClassName: 'Calculator',
    defaultConfig: { enabled: true, order: 400 },
  },

  // ── Plot Analysis ──────────────────────────────────────────────────────────
  {
    configKey: 'EciPlot',
    ossImport: () => import('./plot-analysis/eci-plots'),
    ossClassName: 'EciPlot',
    defaultConfig: { enabled: true, order: 260 },
  },
  {
    configKey: 'EcfPlot',
    ossImport: () => import('./plot-analysis/ecf-plots'),
    ossClassName: 'EcfPlot',
    defaultConfig: { enabled: true, order: 261 },
  },
  {
    configKey: 'RicPlot',
    ossImport: () => import('./plot-analysis/ric-plots'),
    ossClassName: 'RicPlot',
    defaultConfig: { enabled: true, order: 262 },
  },
  {
    configKey: 'Time2LonPlots',
    ossImport: () => import('./plot-analysis/time2lon'),
    ossClassName: 'Time2LonPlots',
    proImport: () => import('../plugins-pro/plot-analysis/time2lon'),
    proClassName: 'Time2LonPlotsPro',
    defaultConfig: { enabled: true, order: 263 },
  },
  {
    configKey: 'Lat2LonPlots',
    ossImport: () => import('./plot-analysis/lat2lon'),
    ossClassName: 'Lat2LonPlots',
    defaultConfig: { enabled: true, order: 264 },
  },
  {
    configKey: 'Inc2AltPlots',
    ossImport: () => import('./plot-analysis/inc2alt'),
    ossClassName: 'Inc2AltPlots',
    defaultConfig: { enabled: true, order: 265 },
  },
  {
    configKey: 'Inc2LonPlots',
    ossImport: () => import('./plot-analysis/inc2lon'),
    ossClassName: 'Inc2LonPlots',
    defaultConfig: { enabled: true, order: 266 },
  },

  // ── Settings & Utility ─────────────────────────────────────────────────────
  {
    configKey: 'FilterMenuPlugin',
    ossImport: () => import('./filter-menu/filter-menu'),
    ossClassName: 'FilterMenuPlugin',
    defaultConfig: { enabled: true, order: 592 },
  },
  {
    configKey: 'SymbologyPlugin',
    ossImport: () => import('./symbology/symbology-plugin'),
    ossClassName: 'SymbologyPlugin',
    proImport: () => import('../plugins-pro/symbology/symbology-plugin'),
    defaultConfig: { enabled: true, order: 593 },
  },
  {
    configKey: 'SettingsMenuPlugin',
    ossImport: () => import('./settings-menu/settings-menu'),
    ossClassName: 'SettingsMenuPlugin',
    defaultConfig: { enabled: true, order: 590 },
  },
  {
    configKey: 'GraphicsMenuPlugin',
    ossImport: () => import('./graphics-menu/graphics-menu'),
    ossClassName: 'GraphicsMenuPlugin',
    proImport: () => import('../plugins-pro/graphics-menu/graphics-menu'),
    defaultConfig: { enabled: true, order: 591 },
  },
  {
    configKey: 'GamepadPlugin',
    ossImport: () => import('./gamepad/gamepad'),
    ossClassName: 'GamepadPlugin',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'VideoDirectorPlugin',
    ossImport: () => import('./video-director/video-director'),
    ossClassName: 'VideoDirectorPlugin',
    defaultConfig: { enabled: true, order: 510 },
  },
  {
    configKey: 'AboutMenuPlugin',
    ossImport: () => import('./about-menu/about-menu'),
    ossClassName: 'AboutMenuPlugin',
    proImport: () => import('../plugins-pro/about-menu/about-menu'),
    defaultConfig: { enabled: false, order: 601 },
  },
  {
    configKey: 'EarthPresetsPlugin',
    ossImport: () => import('./earth-presets/earth-presets'),
    ossClassName: 'EarthPresetsPlugin',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'DrawLinesPlugin',
    ossImport: () => import('./draw-lines/draw-lines'),
    ossClassName: 'DrawLinesPlugin',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'ViewInfoRmbPlugin',
    ossImport: () => import('./view-info-rmb/view-info-rmb'),
    ossClassName: 'ViewInfoRmbPlugin',
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'VcrPlugin',
    ossImport: () => import('./vcr/vcr'),
    ossClassName: 'VcrPlugin',
    defaultConfig: { enabled: true, order: 1000 },
  },
  {
    configKey: 'CommandPalettePlugin',
    ossImport: () => import('./command-palette/command-palette'),
    ossClassName: 'CommandPalettePlugin',
    proImport: () => import('../plugins-pro/command-palette/command-palette'),
    defaultConfig: { enabled: true },
  },
  {
    configKey: 'FavoritesMenuPlugin',
    ossImport: () => import('./favorites-menu/favorites-menu'),
    ossClassName: 'FavoritesMenuPlugin',
    proImport: () => import('../plugins-pro/favorites-menu/favorites-menu'),
    defaultConfig: { enabled: true },
  },
];
